POST http://localhost:3000/v1/products
Content-Type: application/json

{
  "name": "Liquidifcador",
  "price": 100.4,
  "description": "Melhor liquidificador do mercado",
  "image": "http://minhaloja.com/liqui.jpg",
  "quantity": 10
}