PUT http://localhost:3000/products/1
Content-Type: application/json

{
  "name": "Geladeira",
  "price": 10000,
  "description": "Smart fridge",
  "image": "http://minhaloja.com/jpg",
  "quantity": 4
}